buildscript {
    repositories {
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        google()
    }
}

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.compose) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.ksp)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.detekt)

    alias(libs.plugins.sentry)
    alias(libs.plugins.buildconfig)
    alias(libs.plugins.versions)
    alias(libs.plugins.kover)
}

val koverMeasuredProjects = listOf("cereal-client", "cereal-licensing")

dependencies {
    koverMeasuredProjects.forEach { kover(project(":$it")) }
}

kover {
    reports {
        filters {
            excludes {
                // Generated by the buildconfig plugin.
                classes("*.BuildConfig")
                // Compose UI — not exercised by unit tests; ViewModels carry the testable logic.
                annotatedBy("androidx.compose.runtime.Composable")
                // Application entry point / wiring.
                classes("com.cereal.client.presentation.MainKt")
                // Generated by the Room compiler (DAO/database `_Impl` classes). These are exercised
                // by the Room data-source integration tests but their generated branches are not
                // hand-written, so they are excluded from coverage like other generated code above.
                classes("*_Impl")
                classes("*_Impl\$*")
            }
        }
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven("https://maven.pkg.jetbrains.space/public/p/compose/dev")
        google()
        maven("https://oss.sonatype.org/content/repositories/snapshots")
        maven("https://maven.cereal-automation.com/releases")
    }
}

subprojects {
    apply(plugin = "org.jlleitschuh.gradle.ktlint")
    apply(plugin = "io.gitlab.arturbosch.detekt")

    if (name in koverMeasuredProjects) {
        apply(plugin = "org.jetbrains.kotlinx.kover")
    }

    configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        version.set("1.8.0")
        additionalEditorconfig.set(
            mapOf(
                "max_line_length" to "off",
                "ktlint_function_naming_ignore_when_annotated_with" to "Composable",
                "ktlint_standard_filename" to "disabled",
            ),
        )
        filter {
            exclude {
                it.file.path.contains(
                    layout.buildDirectory
                        .dir("generated")
                        .get()
                        .toString(),
                ) ||
                    it.file.path.contains("${rootProject.projectDir}/cereal-client/sekret")
            }
            include("**/kotlin/**")
        }
    }

    configure<io.gitlab.arturbosch.detekt.extensions.DetektExtension> {
        // Start from detekt's defaults and layer our overrides on top.
        buildUponDefaultConfig = true
        config.setFrom(rootProject.file("config/detekt/detekt.yml"))
        // Per-module baseline lets us adopt detekt without fixing every pre-existing
        // finding up front. Generate with `./gradlew detektBaseline`. A missing file
        // is ignored, so this is safe before the baselines exist.
        baseline = rootProject.file("config/detekt/baseline-${project.name}.xml")
        parallel = true
    }

    tasks.withType<io.gitlab.arturbosch.detekt.Detekt>().configureEach {
        jvmTarget = "21"
        // Skip generated sources and the Sekret subproject, mirroring the ktlint filter.
        exclude {
            it.file.path.contains(
                layout.buildDirectory
                    .dir("generated")
                    .get()
                    .toString(),
            ) ||
                it.file.path.contains("${rootProject.projectDir}/cereal-client/sekret")
        }
        reports {
            html.required.set(true)
            sarif.required.set(true)
            xml.required.set(false)
            txt.required.set(false)
            md.required.set(false)
        }
    }

    tasks.withType<io.gitlab.arturbosch.detekt.DetektCreateBaselineTask>().configureEach {
        jvmTarget = "21"
    }
}

sentry {
    // Generates a JVM (Java, Kotlin, etc.) source bundle and uploads your source code to Sentry.
    // This enables source context, allowing you to see your source
    // code as part of your stack traces in Sentry.
    includeSourceContext.set(project.properties["sentry_auth_token"] != null)

    org.set("cereal")
    projectName.set("cereal-client")
    authToken.set("${project.properties["sentry_auth_token"]}")
}

// Configure the gradle-versions-plugin to only show stable versions
tasks.withType<com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask> {
    rejectVersionIf {
        isNonStable(candidate.version) && !isNonStable(currentVersion)
    }
}

fun isNonStable(version: String): Boolean {
    val stableKeyword = listOf("RELEASE", "FINAL", "GA").any { version.uppercase().contains(it) }
    val regex = "^[0-9,.v-]+(-r)?$".toRegex()
    val isStable = stableKeyword || regex.matches(version)
    return isStable.not()
}
